(define (typeof x)
  (cond
   ((symbol? x) 'symbol)
   ((boolean? x) 'boolean)
   ((integer? x) 'integer)
   ((real? x) 'real)
   ((number? x) 'number)
   ((char? x) 'char)
   ((string? x) 'string)
   ((null? x)  'null)
   ((list? x) 'list)
   ((pair? x) 'pair)
   ((vector? x) 'vector)
   ((procedure? x) 'procedure)
   (else 'object)))
   
(typeof 1)
(typeof 1.2)
(typeof #t)
(typeof #f)
(typeof #\a)
(typeof "ss")
(typeof '+)
(typeof +)
(typeof '())
(typeof '(1 2 3 . 4))
(typeof '(1 2 3 4))
(typeof #(1 2 3 4))