(define (string-first-char-upcase s)
  (let ((s1 (string-copy s)))
    (string-set! s1 0 (char-upcase (string-ref s 0)))
    s1))


;类定义
(define (def-vo name properties)
  (cons name properties))
(define (vo-name class) (car class))
(define (vo-props class) (cdr class))

;属性定义
(define (def-props props) props)
(define (prop-name prop) (car prop))
(define (prop-type prop) (cadr prop))

(define (vo-fields-write props)
  (for-each
   (lambda (prop)
     (display "    ")
     (display "private ")
     (display (prop-type prop))
     (display " ")
     (display (prop-name prop))
     (display ";")
     (newline))
   props))
(define (vo-selector-write props)
  (for-each
   (lambda (prop)
     (define propName (symbol->string-ci (prop-name prop)))
     
     (display "    ")
     (display "public ")
     (display "void")
     (display " ")
     (display (string-append "set" (string-first-char-upcase propName)))
     (display "(")
     (display (prop-type prop))
     (display " ")
     (display (prop-name prop))
     (display ")")
     (display "{")
     (newline)
     (display "    ")
     (display "    ")
     (display (string-append "this." propName))
     (display " ")
     (display "=")
     (display " ")
     (display propName)
     (display ";")
     (newline)
     (display "    ")
     (display "}")
     
     (newline)
     (display "    ")
     (display "public ")
     (display (prop-type prop))
     (display " ")
     (display (string-append "get" (string-first-char-upcase propName)))
     (display "(")
     (display ")")
     (display "{")
     (newline)
     (display "    ")
     (display "    ")
     (display "return ")
     (display propName)
     (display ";")
     (newline)
     (display "    ")
     (display "}")
     
     (newline))
   props))
(define (vo-write class)
  (display "public class ")
  (display (vo-name class))
  (display " {")
  (newline)
  (vo-fields-write (vo-props class))
  (newline)
  (vo-selector-write (vo-props class))
  (display "}"))


      
(vo-write
 (def-vo 'Dog
   (def-props
     '((legs int)
       (name String)))))