(define (consi x y)
  (* (expt 2 x) (expt 3 y)))
(define (cari z)
    (if (= 0 (remainder z 2))
        (+ 1 (cari (/ z 2)))
        0))
(define (cdri z)
    (if (= 0 (remainder z 3))
        (+ 1 (cdri (/ z 3)))
        0))

(define z (consi 1 2))
(cari z)
(cdri z)

(define a (consi 3 (consi 5 2)))
(cari a)
(cari (cdri a))
(cdri (cdri a))